#!/bin/sh
# a container from $BRIC_IMAGE (default tools) with only the scratch directory mounted
exec docker run --rm -i --init -v "$PWD":"$PWD" -w "$PWD" -e BRIC_DB -e PATH="$PWD/bin:/usr/local/bin:/usr/bin:/bin" "${BRIC_IMAGE:-tools}" sh "$1"
