#!/bin/sh
# macos: read anywhere, write only the scratch directory, network open
exec sandbox-exec -p "(version 1) (allow default) (deny file-write*) (allow file-write* (subpath \"$PWD\") (subpath \"/dev\"))" sh "$1"
